// import Navbar from "@/components/Navbar";
// import "./globals.css";
// import Footer from "@/components/Footer";


// export const metadata = {
//   title: "Payroll",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`antialiased`}>
//         <Navbar />
//         {children}
//         <Footer />
//         </body>
//     </html>
//   );
// }

import ClientLayoutWrapper from "@/components/ClientLayoutWrapper";
import "./globals.css";


export const metadata = {
  title: "Payroll Management Services – Accurate, Compliant & Automated | Workforce",
  description:
    "Streamline your payroll with fully automated processing, 100% compliance, accurate salary calculations, payslips, WPS, TDS, PF/ESIC filings, reimbursements, and employee self-service. Designed for startups, SMEs, and enterprises.",
  keywords: [
    "Payroll services",
    "Payroll management",
    "Payroll outsourcing",
    "Payroll compliance",
    "Salary processing",
    "Automated payroll",
    "PF ESIC TDS filings",
    "WPS payroll UAE",
    "End-to-end payroll solutions"
  ],
  alternates: {
    canonical: "https://www.yourdomain.com/payroll",
  },
  openGraph: {
    title: "Payroll Management Services – Accurate & Compliant",
    description:
      "Automated & compliant payroll services with accurate salary processing, tax filings, WPS, PF/ESIC, and employee self-service.",
    url: "https://www.yourdomain.com/payroll",
    siteName: "Workforce",
    images: [
      {
        url: "https://www.yourdomain.com/og-payroll.jpg",
        width: 1200,
        height: 630,
        alt: "Payroll Management Solutions",
      },
    ],
    locale: "en_IND",
    type: "website",
  },
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ClientLayoutWrapper>{children}</ClientLayoutWrapper>
      </body>
    </html>
  );
}

