// import Navbar from "@/components/Navbar";
// import "./globals.css";
// import Footer from "@/components/Footer";


// export const metadata = {
//   title: "Payroll",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body className={`antialiased`}>
//         <Navbar />
//         {children}
//         <Footer />
//         </body>
//     </html>
//   );
// }

import ClientLayoutWrapper from "@/components/ClientLayoutWrapper";
import "./globals.css";


export const metadata = {
  title: "Payroll",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="antialiased">
        <ClientLayoutWrapper>{children}</ClientLayoutWrapper>
      </body>
    </html>
  );
}

